### ISSUE TITLE
általános css tanácsok

### ISSUE THREAD

**Issue by cerberus2477** [OOGGZZII/plamnt#72]
so, i'll share my wisdom
( todoban van, hátha így elolvasódik c: )

### container méret
ha van egy container és abban egy dolog, akkor nem a container méretét szoktuk megadni (meg a dologét is).
- a containernek van egy paddingje, a dolognak meg egy mérete.
    -  ez a méret is a legtöbbször nem expliciten megadott, hanem felveszi pl a benne lévő szöveg nagyságát. 
    -  ahol lehet inkább `max-width`-et vagy `min-width`-et adjunk meg, nagyon ritkán van egy dolognak fix mérete.
  
így nem az lesz hogy van egy x méretű doboz amiben "lebeg" egy y méretű dolog, kiszámíthatalan és függőlegesen és vízszintesen is középre kell helyezni a legtöbbször.

***pl:***

```css
.searchbar {
    margin-left: auto;
    margin-right: auto;
    height: 10vh;
    width: 80%;
    padding: 1%;
}

.searchbar input {
    width: 80%;
    height: 40%;
}
```

***helyett legyen***
```css
.searchbar {
    display: flex;
    gap: 1rem;
    width: 100%;
    padding: 1rem;
}

.searchbar input {
    flex: 1;
}
```

### mértékegységek
nem igazán használunk `vw` és `vh` unitokat. általában csak több vele a probléma.
- `rem` (`em`) % (ez leginkább 100%, nem fog "kiérni a szélekre" ahol nem szeretnénk, merta containernek van egy paddingje)
- ha azt akarod hogy "100%" helyet kitöltse a dolog *ami elérhető neki* akkor érdemes `flexbox`ot használni a konténeren és a dolgon `flex:1`-et, lásd feljebb. így pl a keresésgomb nem csúszik új sorba.
